version: '3.7'
services:
  meshery:
    image: khulnasoft/meshplay:stable-latest
    labels:
      - ${labels.watchtower}
    environment:
      - "PROVIDER_BASE_URLS=https://meshery.layer5.io"
      - "ADAPTER_URLS=meshery-istio:10000 meshery-linkerd:10001 meshery-consul:10002 meshery-octarine:10003 meshery-nsm:10004"
      - "EVENT=mesheryLocal"
    ports:
      - "${meshery.port}:8080"
  meshery-istio:
    image: khulnasoft/meshplay-istio:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${istio.port}:10000"
    x-enabled: ${istio.enabled}
  meshery-linkerd:
    image: khulnasoft/meshplay-linkerd:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${linkerd.port}:10001"
    x-enabled: ${linkerd.enabled}
  meshery-consul:
    image: khulnasoft/meshplay-consul:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${consul.port}:10002"
    x-enabled: ${consul.enabled}
  meshery-octarine:
    image: khulnasoft/meshplay-octarine:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${octarine.port}:10003"
    x-enabled: ${octarine.enabled}     
  meshery-nsm:
    image: khulnasoft/meshplay-nsm:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${nsm.port}:10004"
    x-enabled: ${nsm.enabled}
  meshery-cpx:
    image: khulnasoft/meshplay-cpx:stable-latest
    labels:
      - ${labels.watchtower}
    ports:
      - "${cpx.port}:10000"
    x-enabled: ${cpx.enabled}
  watchtower:
    image: containrrr/watchtower
    labels:
      - ${labels.watchtower}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
