apiVersion: meshplay.layer5.io/v1alpha1
kind: MeshSync
metadata:
  name: meshplay-meshsync
  namespace: meshplay
  labels:
    app: meshplay
    component: controller
    version: v0.1.15
  annotations:
    meshplay/component-type: management-plane
spec:
  size: 1
  broker:
    native:
      name: meshplay-broker
      namespace: meshplay